### ISSUE TITLE
acme-bank: ERROR: Failed to create component version: 302 

### ISSUE THREAD

**Issue by raviram203** [ibm-cloud-architecture/refarch-hybridcloud-blueportal-api#2]
Pulled tutorial from [https://github.com/ibm-cloud-architecture/refarch-hybridcloud-blueportal-api](url) and ran it through an on premises installation of Jenkins, UCD Server and {APIC toolkit+UCD Agent}, with API Connect Mgmt server & DP gwy running. Have tried several variations & restarts over the last 8 hours. The errors vary, but the most frequent is "ERROR: Failed to create component version: 302". Does not seem like the source code from github reaches the UCD server. Attached files build8.zip (last build from the jobs directory) and jenkins.log.txt  (stopped jenkins, cleared log to reduce size).

[jenkins.log.txt](https://github.com/ibm-cloud-architecture/refarch-hybridcloud-blueportal-api/files/1253427/jenkins.log.txt)
[build8.zip](https://github.com/ibm-cloud-architecture/refarch-hybridcloud-blueportal-api/files/1253429/build8.zip)

I installed & configured both Jenkins plugins: 
- IBM UrbanCode Deploy Pipeline (Build Steps) Plugin 2.6.929921
- IBM UrbanCode Deploy Plugin  1.9.925586

Seems to use the latter, though the names in the configuration panel are difficult to relate to the Installed list. Help appreciated.

**Comment by raviram203** [comment]
I stumbled on to a remedy. I doubt it is a solution, but will do for now. I modified the UCD server configuration for both Jenkins UCD plugins to `https://<ip>:8443` and enabled `admin user`. The build plugin pushed git code to the UCD server. I was misled by the on screen help "?" button: `The URL of the IBM UrbanCode Deploy server. Eg: http://ibm_ucdeploy.company.com:8080`. Please **modify the on screen help** for the plugins.

**Comment by hollisc** [comment]
Hi @raviram203,

The tutorial uses the `IBM UrbanCode Deploy Pipeline (Build Steps) Plugin`.  

In regards to the Jenkins to UCD connection, you can configure this from Jenkins > Manage Jenkins > Configure System > IBM UrbanCode Deploy Pipeline Plugin Configuration section. 

You can specify the UCD URL (whether its http or https) and the UCD user to use (does not have to be an admin user). 

Hope this helps.
